# CLMM Conda environment
name: clmm
channels:
  - conda-forge
  - defaults
dependencies:
  - python >= 3.8
  - astropy >= 4.0, !=5.0
  - black
  - cmake
  - hatch
  - healpy
  - isort
  - jupyter
  - matplotlib
  - numcosmo <= 0.22.0
  - numpy >= 2.0
  - pandoc
  - pip
  - pyccl >= 3.1.2
  - pylint
  - pytest
  - pytest-cov
  - scipy >= 1.3
  - sphinx
  - sphinx_rtd_theme
  - pip:
    - qp-prob @ git+https://github.com/LSSTDESC/qp.git
    - cluster-toolkit @ git+https://github.com/tmcclintock/cluster_toolkit.git